//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el Servidor, contactese con soporte técnico.
        /// </summary>
        internal static string GLOBAL_ERROR_SERVER {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string LOGIN_LOGIN {
            get {
                return ResourceManager.GetString("LOGIN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        internal static string LOGIN_TITLE_HEADING {
            get {
                return ResourceManager.GetString("LOGIN_TITLE_HEADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        internal static string SIDEBAR_BANK_BANK {
            get {
                return ResourceManager.GetString("SIDEBAR_BANK_BANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financiaciones.
        /// </summary>
        internal static string SIDEBAR_FINANCING_FINANCING {
            get {
                return ResourceManager.GetString("SIDEBAR_FINANCING_FINANCING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulación a Cuenta Venta.
        /// </summary>
        internal static string SIDEBAR_SALES_ACCOUNT_CANCELLATION_SALE {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_ACCOUNT_CANCELLATION_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string SIDEBAR_SALES_CUSTOMERS {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entregar Vehiculo.
        /// </summary>
        internal static string SIDEBAR_SALES_DELIVER_VEHICLE {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_DELIVER_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos Documento.
        /// </summary>
        internal static string SIDEBAR_SALES_DOCUMENT_TYPE {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_DOCUMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listados.
        /// </summary>
        internal static string SIDEBAR_SALES_LISTINGS {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_LISTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimientos.
        /// </summary>
        internal static string SIDEBAR_SALES_MAINTENANSE {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_MAINTENANSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        internal static string SIDEBAR_SALES_ORDERS {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Pedidos.
        /// </summary>
        internal static string SIDEBAR_SALES_ORDER_MANAGEMENT {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_ORDER_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultas.
        /// </summary>
        internal static string SIDEBAR_SALES_QUERIES {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizaciones.
        /// </summary>
        internal static string SIDEBAR_SALES_RATES {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_RATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibir Pedidos.
        /// </summary>
        internal static string SIDEBAR_SALES_RECEIVE_ORDERS {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_RECEIVE_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devolución de Seña.
        /// </summary>
        internal static string SIDEBAR_SALES_RETURN_SIGN {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_RETURN_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        internal static string SIDEBAR_SALES_SALES {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_SALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulación de Venta.
        /// </summary>
        internal static string SIDEBAR_SALES_SALE_CANCELLATION {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_SALE_CANCELLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendedores.
        /// </summary>
        internal static string SIDEBAR_SALES_SELLERS {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_SELLERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A Cuenta Venta Futura.
        /// </summary>
        internal static string SIDEBAR_SALES_TO_FUTURE_SALE_ACCOUNT {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_TO_FUTURE_SALE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehiculos.
        /// </summary>
        internal static string SIDEBAR_SALES_VEHICLES {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_VEHICLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta de Vehiculo.
        /// </summary>
        internal static string SIDEBAR_SALES_VEHICLE_SALE {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_VEHICLE_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seña Vehiculo/Pedido.
        /// </summary>
        internal static string SIDEBAR_SALES_VEHICLE_SIGN_ORDER {
            get {
                return ResourceManager.GetString("SIDEBAR_SALES_VEHICLE_SIGN_ORDER", resourceCulture);
            }
        }
    }
}
